export const GET_ONLOAD_DATA = "GET_ONLOAD_DATA";
export const GET_ONLOAD_DATA_ASYNC = "GET_ONLOAD_DATA_ASYNC";
export const GET_ONLOAD_CATEGORY = "GET_ONLOAD_CATEGORY";
export const GET_ONLOAD_CATEGORY_ASYNC = "GET_ONLOAD_CATEGORY_ASYNC";
export const GET_ITEM_DATA = "GET_ITEM_DATA";
export const GET_ITEM_DATA_ASYNC = "GET_ITEM_DATA_ASYNC";